pid_node:
  ros__parameters:
    kp_yaw: 0.03
    ki_yaw: 0.0
    kd_yaw: 0.0
    kp_pitch: 0.03
    ki_pitch: 0.0
    kd_pitch: 0.0
    kp_roll: 0.03
    ki_roll: 0.0
    kd_roll: 0.0
    setpoint_yaw: 0.0
    setpoint_pitch: 0.0
    setpoint_roll: 0.0

offset_calibrator:
  ros__parameters:
    imu_num_cal_samples: 100

motor_dir_control_node:
  ros__parameters:
    br_order: 6
    bm_order: 1
    fl_order: 3
    fr_order: 2
    ml_order: 5
    bl_order: 7
    mr_order: 4
    br_direction: 1
    bm_direction: 1
    fl_direction: 1
    fr_direction: 1
    ml_direction: 1
    bl_direction: 1
    mr_direction: 1