pid_node:
  ros__parameters:
    kp_yaw: 0.03
    ki_yaw: 0.0
    kd_yaw: 0.0
    kp_pitch: 0.03
    ki_pitch: 0.0
    kd_pitch: 0.0
    kp_roll: 0.03
    ki_roll: 0.0
    kd_roll: 0.0
    setpoint_yaw: 0.0
    setpoint_pitch: 0.0
    setpoint_roll: 0.0

offset_calibrator:
  ros__parameters:
    imu_num_cal_samples: 100