kp_roll: 1.0
ki_roll: 0.0
kd_roll: 1.0
kp_pitch: 1.0
ki_pitch: 0.0
kd_pitch: 0.6
kp_yaw: 1.0
ki_yaw: 0.0
kd_yaw: 0.6
kp_x: 10.0
ki_x: 0.0
kd_x: 5.0
kp_y: 0.0
ki_y: 0.0
kd_y: 0.0
kp_z: 0.0
ki_z: 0.0
kd_z: 0.0
speed_coeff: 0.03
