kp_roll: 1
ki_roll: 0
kd_roll: 1
kp_pitch: 1
ki_pitch: 0
kd_pitch: 0.6
kp_yaw: 1
ki_yaw: 0
kd_yaw: 0.6
kp_fwd: 1
ki_fwd: 0
kd_fwd: 0.5
kp_lat: 1
ki_lat: 0
kd_lat: 0.5
kp_z: 2
ki_z: 0
kd_z: 0.5
speed_coeff: 0.03
