# See: https://github.com/gazebosim/ros_gz/tree/ros2/ros_gz_bridge#example-5-configuring-the-bridge-via-yaml
- ros_topic_name: /gz/keyboard/keypress
  gz_topic_name: /keyboard/keypress
  ros_type_name: std_msgs/msg/Int32
  direction: GZ_TO_ROS
  gz_type_name: gz.msgs.Int32
- ros_topic_name: /gz/blobfish/imu
  gz_topic_name: /blobfish/imu
  ros_type_name: sensor_msgs/msg/Imu
  gz_type_name: gz.msgs.IMU
  direction: GZ_TO_ROS
  publisher_queue: 0
- ros_topic_name: /gz/blobfish/depth
  gz_topic_name: /blobfish/depth
  ros_type_name: ros_gz_interfaces/msg/Altimeter
  gz_type_name: gz.msgs.Altimeter
  direction: GZ_TO_ROS
  publisher_queue: 0

# For all the thrusters
- ros_topic_name: /gz/blobfish/thruster/FL
  gz_topic_name: /blobfish/thruster/FL
  ros_type_name: std_msgs/msg/Float64
  gz_type_name: gz.msgs.Double
  direction: ROS_TO_GZ
  subscriber_queue: 0
- ros_topic_name: /gz/blobfish/thruster/FR
  gz_topic_name: /blobfish/thruster/FR
  ros_type_name: std_msgs/msg/Float64
  gz_type_name: gz.msgs.Double
  direction: ROS_TO_GZ
  subscriber_queue: 0
- ros_topic_name: /gz/blobfish/thruster/ML
  gz_topic_name: /blobfish/thruster/ML
  ros_type_name: std_msgs/msg/Float64
  gz_type_name: gz.msgs.Double
  direction: ROS_TO_GZ
  subscriber_queue: 0
- ros_topic_name: /gz/blobfish/thruster/MR
  gz_topic_name: /blobfish/thruster/MR
  ros_type_name: std_msgs/msg/Float64
  gz_type_name: gz.msgs.Double
  direction: ROS_TO_GZ
  subscriber_queue: 0
- ros_topic_name: /gz/blobfish/thruster/BL
  gz_topic_name: /blobfish/thruster/BL
  ros_type_name: std_msgs/msg/Float64
  gz_type_name: gz.msgs.Double
  direction: ROS_TO_GZ
  subscriber_queue: 0
- ros_topic_name: /gz/blobfish/thruster/BR
  gz_topic_name: /blobfish/thruster/BR
  ros_type_name: std_msgs/msg/Float64
  gz_type_name: gz.msgs.Double
  direction: ROS_TO_GZ
  subscriber_queue: 0
- ros_topic_name: /gz/blobfish/thruster/BM
  gz_topic_name: /blobfish/thruster/BM
  ros_type_name: std_msgs/msg/Float64
  gz_type_name: gz.msgs.Double
  direction: ROS_TO_GZ
  subscriber_queue: 0
