ARG BASE_IMAGE
FROM ${BASE_IMAGE}

# Add the arduino-cli command.
RUN curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | BINDIR=/usr/local/bin sh

# Nvidia ISAAC's `.user` layer adds a new user, arduino has to be installed for that user.
USER admin
RUN arduino-cli core install arduino:avr
RUN arduino-cli lib install SimpleSerialProtocol Servo
USER root
