ARG BASE_IMAGE
FROM ${BASE_IMAGE}

# Add the arduino-cli command
COPY arduino-cli /bin

# TODO organise these dependencies
# Install tmux for easier use, pyserial for Serial comms with the Arduino, and some Arduino deps

# TODO add pyserial to rosdep for that package instead
RUN sudo apt update
RUN sudo apt install tmux
RUN pip install pyserial

# Bug: these commands don't work for some reason
RUN arduino-cli core install arduino:avr
RUN arduino-cli lib install SimpleSerialProtocol Servo
