usb_cam:
  ros__parameters:
    # TODO: similar to arduino_launch.py, filtering cameras should be possible.
    video_device: /dev/video0
    framerate: 60.0
    image_width: 640
    image_height: 480
    brightness: 100
    contrast: 100
    saturation: 50
    sharpness: 100
    gain: -1
    auto_white_balance: True
    white_balance: 4000
    auto_exposure: True
    exposure: -1
    auto_focus: True
    # NOTE: usb cams typically don't have software-controllable focus (ours don't).
    focus: -1
