thruster_manager:
  ros__parameters:
    br_order: 6
    bm_order: 1
    fl_order: 3
    fr_order: 2
    ml_order: 5
    bl_order: 7
    mr_order: 4
    br_direction: 1
    bm_direction: 1
    fl_direction: 1
    fr_direction: 1
    ml_direction: 1
    bl_direction: 1
    mr_direction: 1
    