- speed: [0.0, 0.0, -0.5]


# For testing the routine node itself.
# - speed: [0.0, 0.0, 0.0]
# - rph: [0.0, 0.0, 0.0]
# - wait: 1
# - speed: [0.0, 0.0, -0.235]
# - rph: [0.0, 0.0, 90]
# - wait: 5
# - rph: [0.0, 0.0, -90]
# - wait: 5
# - speed: [0.0, 0.0, -0.4]
# - wait: 5
# - speed: [0.0, 0.0, 0.4]
# - wait: 4
# - speed: [0.0, 0.0, 0.0]
# - rph: [0.0, 0.0, 0.0]
