thruster_manager:
  ros__parameters:
    br_order: 1
    bm_order: 2
    fl_order: 3
    fr_order: 4
    bl_order: 5
    br_order: 6
    bm_order: 7
    br_direction: 1
    bm_direction: 1
    fl_direction: 1
    fr_direction: 1
    bl_direction: 1
    br_direction: 1
    bm_direction: 1
    