<?xml version="1.0"?>
<!-- Copyright (c) 2016 The UUV Simulator Authors.
     All rights reserved.

     Licensed under the Apache License, Version 2.0 (the "License");
     you may not use this file except in compliance with the License.
     You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

     Unless required by applicable law or agreed to in writing, software
     distributed under the License is distributed on an "AS IS" BASIS,
     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
     See the License for the specific language governing permissions and
     limitations under the License.
-->
<robot name="beluga" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:macro name="beluga_base" params="namespace debug inertial_reference_frame">

  <!-- Import xacros -->
  <xacro:include filename="common.urdf.xacro"/>
  <xacro:include filename="sensor_snippets.xacro"/>
  <xacro:include filename="thruster_snippets.xacro"/>
  
  <!-- Define Parameters -->
  <xacro:property name="mass" value="20"/>
  <xacro:property name="volume" value="0.011054"/>
  <xacro:property name="cog" value="0 0.005 -.03"/>
  <xacro:property name="cob" value="0 0 0"/>
  <xacro:property name="rho" value="1028"/>

  <xacro:property name="x_size" value="0.448"/>
  <xacro:property name="y_size" value="0.2384"/>
  <xacro:property name="z_size" value="0.28066"/>

  <xacro:property name="equivalent_radius" value="${0.5*z_size}"/>
    
  <link name="${namespace}/base_link">
    <inertial>
      <mass value="${mass}"/>
      <origin xyz="${cog}" rpy = "0 0 0"/>
      <inertia ixx="0.26"  iyy="0.40"  izz="0.35"
               ixy="0.001" iyz="0.001" ixz="0.02"/>
    </inertial>
    
    <!-- Main Body -->
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.48538 0.27 0.327"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.6 0.47 0.36"/>
      </geometry>
    </collision>

    <!-- Left Front Thruster Mount -->
    <visual>
      <origin xyz="0.27043 0.195 -0.025" rpy="0 0 -${pi}"/>
        <geometry>
          <mesh filename="file://../meshes/angled_thruster_mount.dae" scale="0.001 0.001 0.001"/>
        </geometry>
    </visual>

    <!-- Right Front Thruster Mount -->
    <visual>
      <origin xyz="0.27043 -0.195 0.025" rpy="${pi} 0 -${pi}"/>
        <geometry>
          <mesh filename="file://../meshes/angled_thruster_mount.dae" scale="0.001 0.001 0.001"/>
        </geometry>
    </visual>

    <!-- Left Back Thruster Mount -->
    <visual>
      <origin xyz="-0.27043 0.195 0.025" rpy="0 ${pi} -${pi}"/>
        <geometry>
          <mesh filename="file://../meshes/angled_thruster_mount.dae" scale="0.001 0.001 0.001"/>
        </geometry>
    </visual>

    <!-- Right Back Thruster Mount -->
    <visual>
      <origin xyz="-0.27043 -0.195 -0.025" rpy="0 0 0"/>
        <geometry>
          <mesh filename="file://../meshes/angled_thruster_mount.dae" scale="0.001 0.001 0.001"/>
        </geometry>
    </visual>

    <!-- Left Middle Thruster Mount -->
    <visual>
      <origin xyz="0 0.165 -0.035" rpy="0 0 0"/> 
      <geometry>
        <box size="0.09 0.06 0.05"/>
      </geometry>
    </visual>

    <!-- Right Middle Thruster Mount -->
    <visual>
      <origin xyz="0 -0.165 -0.035" rpy="0 0 0"/> 
      <geometry>
        <box size="0.05 0.06 0.05"/>
      </geometry>
    </visual>

    <!-- Middle Back Thruster Mount -->
    <visual>
      <origin xyz="-0.26769 0 0.1336" rpy="0 0 0"/> 
      <geometry>
        <box size="0.05 0.05 0.05"/>
      </geometry>
    </visual>
    
  </link>

  <link name="base_link"/>

  <joint name="${namespace}/dummy_joint" type="fixed">
     <parent link="base_link"/>
     <child link="${namespace}/base_link"/>
  </joint>

  <gazebo reference="${namespace}/base_link">
    <selfCollide>false</selfCollide> 
  </gazebo>

  <!-- Set up hydrodynamics plugin -->
  <gazebo>
    <plugin name="${namespace}_uuv_plugin" filename="libuuv_underwater_object_ros_plugin.so">
      <fluid_density>${rho}</fluid_density>
      <flow_velocity_topic>hydrodynamics/current_velocity</flow_velocity_topic>
      <debug>${debug}</debug>
      <link name="${namespace}/base_link">
        <neutrally_bouyant>0</neutrally_bouyant>
        <volume>${volume}</volume>
        <box>
          <width>${y_size}</width>
          <length>${x_size}</length>
          <height>${z_size}</height>
        </box>
        <center_of_buoyancy>${cob}</center_of_buoyancy>
          <hydrodynamic_model>
            <type>fossen</type>
            <added_mass>
              3.899   -0.034  -0.517  0.043   -0.828  -0.039
              -0.034  6.110   0.256   2.047   -0.029  0.314
              -0.517  0.256   18.300  0.031   -1.932  0.054
              0.043   2.047   0.031   1.675   -0.050  0.105
              -0.828  -0.029  -1.932  -0.050  2.213   -0.006
              -0.039  0.314   0.054   0.105   -0.006  0.622
            </added_mass>
            <linear_damping>
              -9.352  -8.685  -91.050 -10 -10 -5
            </linear_damping>
            <quadratic_damping>
              -93.528 -124.066 -227.626 -20 -20 -15
            </quadratic_damping>
          </hydrodynamic_model>
        </link>
      </plugin>
    </gazebo>

    <xacro:include filename="beluga_thrusters.xacro"/>
    <xacro:include filename="beluga_sensors.xacro"/>

  </xacro:macro>
</robot>
